### ISSUE TITLE
Showcase crashes with orientation changes

### ISSUE THREAD

**Issue by VictorAlbertos** [cookpad/BottomNavWatson#16]
## Current Behaviour :cry:
Changing orientation causes showcases crash. 

## Expected behavior :smiley:
Watson should handle properly config changes. 

## Additional information :spiral_notepad:
Stacktrace: 
```
java.lang.IllegalStateException: FragmentManager has been destroyed
at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1783)
at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1814)
at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
at watson.MultipleBackStacksViewModel.obtainNavHostFragment(MultipleBackStacksViewModel.kt:198)
at watson.MultipleBackStacksViewModel.onBottomNavigationView(MultipleBackStacksViewModel.kt:64)
at watson.BottomNavWatsonKt.setupWithNavController(BottomNavWatson.kt:44)
at watson.BottomNavWatsonKt.setupWithNavController$default(BottomNavWatson.kt:21)
at cookpad.com.bottomnavwatson.HomeActivity.onCreate(HomeActivity.kt:12)
at android.app.Activity.performCreate(Activity.java:7989)
at android.app.Activity.performCreate(Activity.java:7978)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:702)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3315)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5358)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5266)
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7476)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:939)
```

**Comment by VictorAlbertos** [comment]
Done
